#from resources.layout.python.window_main import *
import sys, os
from MainWindowPresenter import MainWindowPresenter
from PyQt6 import QtCore, QtGui, QtWidgets

presenter = MainWindowPresenter()

# app = QtWidgets.QApplication(sys.argv)
# MainWindow = QtWidgets.QMainWindow()
# ui = Ui_MainWindow()
# ui.setupUi(MainWindow)
#
# ui.one_button.clicked.connect(presenter.button_clicked)
#
# MainWindow.show()
# sys.exit(app.exec_())

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        iconsDir = os.path.dirname(os.path.abspath(__file__))
        iconsDir = iconsDir.replace("\\", "/")
        iconsDir = iconsDir.replace("python/presentation/view", "resources/icons/")

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 591)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoPicture = QtWidgets.QLabel(parent=self.centralwidget)
        self.logoPicture.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.logoPicture.setText("")
        self.logoPicture.setPixmap(QtGui.QPixmap(iconsDir + "JofLangIcon.png"))
        self.logoPicture.setScaledContents(True)
        self.logoPicture.setObjectName("logoPicture")
        self.categoryName = QtWidgets.QLabel(parent=self.centralwidget)
        self.categoryName.setGeometry(QtCore.QRect(70, 29, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.categoryName.setFont(font)
        self.categoryName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.categoryName.setObjectName("categoryName")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 30, 121, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.runButton.setMinimumSize(QtCore.QSize(30, 30))
        self.runButton.setMaximumSize(QtCore.QSize(30, 30))
        self.runButton.setText("")
        self.runButton.setPixmap(QtGui.QPixmap(iconsDir + "Run.svg"))
        self.runButton.setScaledContents(True)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.bugButton = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.bugButton.setMinimumSize(QtCore.QSize(30, 30))
        self.bugButton.setMaximumSize(QtCore.QSize(30, 30))
        self.bugButton.setText("")
        self.bugButton.setPixmap(QtGui.QPixmap(iconsDir + "Debug.svg"))
        self.bugButton.setScaledContents(True)
        self.bugButton.setObjectName("bugButton")
        self.horizontalLayout.addWidget(self.bugButton)
        self.stopButton = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.stopButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stopButton.setMaximumSize(QtCore.QSize(30, 30))
        self.stopButton.setText("")
        self.stopButton.setPixmap(QtGui.QPixmap(iconsDir + "Stop.svg"))
        self.stopButton.setScaledContents(True)
        self.stopButton.setObjectName(iconsDir + "stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.tableView_3 = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_3.setGeometry(QtCore.QRect(230, 70, 341, 491))
        self.tableView_3.setObjectName("tableView_3")
        self.tableView_4 = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_4.setGeometry(QtCore.QRect(570, 70, 231, 241))
        self.tableView_4.setObjectName("tableView_4")
        self.tableView_5 = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_5.setGeometry(QtCore.QRect(570, 310, 231, 251))
        self.tableView_5.setObjectName("tableView_5")
        self.tableView_6 = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_6.setGeometry(QtCore.QRect(70, 560, 161, 31))
        self.tableView_6.setObjectName("tableView_6")
        self.tableView_7 = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_7.setGeometry(QtCore.QRect(230, 560, 341, 31))
        self.tableView_7.setObjectName("tableView_7")
        self.tableView_8 = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_8.setGeometry(QtCore.QRect(570, 560, 231, 31))
        self.tableView_8.setObjectName("tableView_8")
        self.categoriesList = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.categoriesList.setGeometry(QtCore.QRect(0, 70, 71, 521))
        self.categoriesList.setMaximumSize(QtCore.QSize(71, 521))
        self.categoriesList.setAutoFillBackground(False)
        self.categoriesList.setLineWidth(1)
        self.categoriesList.setShowGrid(True)
        self.categoriesList.setWordWrap(True)
        self.categoriesList.setCornerButtonEnabled(True)
        self.categoriesList.setObjectName("categoriesList")
        self.categoriesList.setColumnCount(0)
        self.categoriesList.setRowCount(6)
        self.categoriesList.setColumnWidth(0, 1)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(iconsDir + "Operators.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon)
        self.categoriesList.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(iconsDir + "Control_2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon1)
        self.categoriesList.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(iconsDir + "Control_1.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon2)
        self.categoriesList.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(iconsDir + "Schema.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon3)
        self.categoriesList.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(iconsDir + "Variable.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon4)
        self.categoriesList.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(iconsDir + "Special.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon5)
        self.categoriesList.setVerticalHeaderItem(5, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(70, 70, 161, 491))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.helpBarButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.helpBarButton.setGeometry(QtCore.QRect(264, 0, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpBarButton.sizePolicy().hasHeightForWidth())
        self.helpBarButton.setSizePolicy(sizePolicy)
        self.helpBarButton.setObjectName("helpBarButton")
        self.executeBarButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.executeBarButton.setGeometry(QtCore.QRect(133, 0, 81, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.executeBarButton.sizePolicy().hasHeightForWidth())
        self.executeBarButton.setSizePolicy(sizePolicy)
        self.executeBarButton.setObjectName("executeBarButton")
        self.optionsBarButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.optionsBarButton.setGeometry(QtCore.QRect(214, 0, 50, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsBarButton.sizePolicy().hasHeightForWidth())
        self.optionsBarButton.setSizePolicy(sizePolicy)
        self.optionsBarButton.setObjectName("optionsBarButton")
        self.fileBarButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fileBarButton.setGeometry(QtCore.QRect(75, 0, 58, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileBarButton.sizePolicy().hasHeightForWidth())
        self.fileBarButton.setSizePolicy(sizePolicy)
        self.fileBarButton.setObjectName("fileBarButton")
        self.logoPicture.raise_()
        self.categoryName.raise_()
        self.horizontalLayoutWidget.raise_()
        self.tableView_3.raise_()
        self.tableView_4.raise_()
        self.tableView_5.raise_()
        self.tableView_6.raise_()
        self.tableView_7.raise_()
        self.tableView_8.raise_()
        self.tableWidget_2.raise_()
        self.categoriesList.raise_()
        self.helpBarButton.raise_()
        self.executeBarButton.raise_()
        self.optionsBarButton.raise_()
        self.fileBarButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.categoryName.setText(_translate("MainWindow", "Название категории"))
        item = self.categoriesList.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Math"))
        item = self.categoriesList.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ifs"))
        item = self.categoriesList.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fors"))
        item = self.categoriesList.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Schema"))
        item = self.categoriesList.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Variables"))
        item = self.categoriesList.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Special"))
        self.helpBarButton.setText(_translate("MainWindow", "Помощь"))
        self.executeBarButton.setText(_translate("MainWindow", "Выполнение"))
        self.optionsBarButton.setText(_translate("MainWindow", "Опции"))
        self.fileBarButton.setText(_translate("MainWindow", "Файл"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
